### ISSUE TITLE
regarding the hdmi/dp audio

### ISSUE THREAD

**Issue by blacksea1206** [mirkcale/hackintosh_asrock_deskmini_h470#1]
Hi mirkcale!

I was hesitating to purchase this one for my Hackintosh.
Since there were some issues with the HDMI/DP audio output.

I just wonder whether you have the same issue or not.

**Comment by mirkcale** [comment]
> Hi mirkcale!
> 
> I was hesitating to purchase this one for my Hackintosh.
> Since there were some issues with the HDMI/DP audio output.
> 
> I just wonder whether you have the same issue or not.

I can't see HDMI/DP output in Mac OS . Yes ,It has.
